name: llama3zh
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - pyyaml
  - requests
  - packaging
  - setuptools
  - wheel

  # PyTorch（CUDA 12.1，適配 Colab）
  - pytorch=2.5.*
  - pytorch-cuda=12.1

  - pip:
      - accelerate
      - datasets
      - transformers
      - peft
      - trl
      - sentencepiece
      - safetensors
      - bitsandbytes
      - tqdm
      - huggingface-hub
